// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkaQzgiePFGEJzDMGZX9NCs_-Z_51_zfI',
    appId: '1:257615843415:web:4034a4895c78efdf891312',
    messagingSenderId: '257615843415',
    projectId: 'smartscalex-7fdc3',
    authDomain: 'smartscalex-7fdc3.firebaseapp.com',
    storageBucket: 'smartscalex-7fdc3.firebasestorage.app',
    measurementId: 'G-YB7FELZ8NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpiyfA_hyF9ureE9DecqSNhF8G9Qp5S8s',
    appId: '1:257615843415:android:7913f94ca07a1112891312',
    messagingSenderId: '257615843415',
    projectId: 'smartscalex-7fdc3',
    storageBucket: 'smartscalex-7fdc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlpWKHVfjCxWL3aWZPF-BIhpWuQt5Dyw',
    appId: '1:257615843415:ios:9d95e0274861b4db891312',
    messagingSenderId: '257615843415',
    projectId: 'smartscalex-7fdc3',
    storageBucket: 'smartscalex-7fdc3.firebasestorage.app',
    iosBundleId: 'com.example.smartscalex',
  );
}
